#!/bin/bash

### BEGIN INIT INFO
# Provides:          tomcat7
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Tomcat7 service
# Description:       Run Tomcat7 service
### END INIT INFO

CATALINA_OPTS="-server -Xms{{tomcat.min_heap_size}} -Xmx{{tomcat.max_heap_size}} -XX:+UseParallelGC -XX:SoftRefLRUPolicyMSPerMB=36000 -XX:+CMSClassUnloadingEnabled -XX:+CMSPermGenSweepingEnabled -XX:MaxPermSize=512m"
CATALINA_PID="{{tomcat.pid_file}}"

cd /opt/tomcat7

case "$1" in
  start)
    echo "Starting Tomcat ..."
    sudo -u tomcat CATALINA_OPTS="${CATALINA_OPTS}" CATALINA_PID="${CATALINA_PID}" ./bin/catalina.sh start
    ;;
  stop)
    echo "Stopping Tomcat ..."
    sudo -u tomcat CATALINA_PID="${CATALINA_PID}" ./bin/catalina.sh stop '{{tomcat.stop_timeout| default(10)}}' -force
    ;;
  *)
    echo "Usage: invoke-rc.d tomcat7 {start|stop}"
    exit 1
    ;;
esac

exit 0

