---

 - include: setup-hostname.yml
 
 - include: install-prereqs.yml
 
 - include: install-docker.yml
 
 - include: configure-docker.yml

 - name: Add user to docker group
   user:
     name: '{{ansible_ssh_user}}'
     groups: docker
     append: yes
   sudo: yes
   sudo_user: root

 - name: Make user-local bin directories
   file: 
     path: ~/bin 
     state: directory


