---

  #
  # Setup hostname
  #

  - name: Set hostname
    shell: echo {{hostname}} >/etc/hostname
    sudo: yes
    sudo_user: root

  - name: Update /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.1\.1'
      line: '127.0.1.1 {{hostname}}'
      owner: root
      group: root
      mode: 0644
    sudo: yes
    sudo_user: root

