---

- name: 'restart-docker'
  systemd:
    name: docker.service
    daemon_reload: yes
    state: restarted
  sudo: yes
  sudo_user: root

- name: 'update-grub'
  shell: update-grub
  sudo: yes
  sudo_user: root

